// <auto-generated />
using System;
using CompenseAgora.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompenseAgora.Migrations
{
    [DbContext(typeof(DataEFContext))]
    [Migration("20251110221953_ProfilePassword")]
    partial class ProfilePassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompenseAgora.Entities.ByBuyEnergyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnnualReference")
                        .HasColumnType("bit");

                    b.Property<decimal>("EficiencyPlantGenerator")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("EnergyTypeCode")
                        .HasColumnType("int");

                    b.Property<string>("Font")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FontDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasEmissionFactor")
                        .HasColumnType("bit");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("QuantityEmissaoCO2BiogenicRemoved")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("QuantityEmissionCO2")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("QuantityEmissionCO2Biogenic")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int?>("TypeEnergyGasID")
                        .HasColumnType("int");

                    b.Property<int>("UnityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenRegistered")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("YearMonth")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EnergyTypeCode");

                    b.HasIndex("TypeEnergyGasID");

                    b.HasIndex("UnityID");

                    b.ToTable("PurchaseEnergy");
                });

            modelBuilder.Entity("CompenseAgora.Entities.ByLocalizationEnergyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnnualReference")
                        .HasColumnType("bit");

                    b.Property<decimal>("EmissionCO2")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<DateTime>("MonthYear")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("UnityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenRegistered")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UnityID");

                    b.ToTable("LocalizationEnergy");
                });

            modelBuilder.Entity("CompenseAgora.Entities.ProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("CompenseAgora.Entities.SolarEnergyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AnnualReference")
                        .HasColumnType("bit");

                    b.Property<string>("DescriptionFont")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Font")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("MonthYear")
                        .HasColumnType("date");

                    b.Property<decimal>("QuantityConsumed")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("QuantityEmissaoCO2")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("QuantityEmissionCO2Biogenic")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("QuantityEmissionCO2BiogenicRemoved")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("QuantityGenerated")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("UnityID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnityID");

                    b.ToTable("SolarEnergy");
                });

            modelBuilder.Entity("CompenseAgora.Entities.TypeEnergyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TypeEnergy");
                });

            modelBuilder.Entity("CompenseAgora.Entities.TypeEnergyGasEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TypeEnergyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeEnergyID");

                    b.ToTable("TypeEnergyGas");
                });

            modelBuilder.Entity("CompenseAgora.Entities.UnityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Unity");
                });

            modelBuilder.Entity("CompenseAgora.Entities.ByBuyEnergyEntity", b =>
                {
                    b.HasOne("CompenseAgora.Entities.TypeEnergyEntity", "TypeEnergyObject")
                        .WithMany()
                        .HasForeignKey("EnergyTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompenseAgora.Entities.TypeEnergyGasEntity", "TypeEnergyGasObject")
                        .WithMany()
                        .HasForeignKey("TypeEnergyGasID");

                    b.HasOne("CompenseAgora.Entities.UnityEntity", "UnityObject")
                        .WithMany()
                        .HasForeignKey("UnityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeEnergyGasObject");

                    b.Navigation("TypeEnergyObject");

                    b.Navigation("UnityObject");
                });

            modelBuilder.Entity("CompenseAgora.Entities.ByLocalizationEnergyEntity", b =>
                {
                    b.HasOne("CompenseAgora.Entities.UnityEntity", "UnityObject")
                        .WithMany()
                        .HasForeignKey("UnityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnityObject");
                });

            modelBuilder.Entity("CompenseAgora.Entities.SolarEnergyEntity", b =>
                {
                    b.HasOne("CompenseAgora.Entities.UnityEntity", "UnityObject")
                        .WithMany()
                        .HasForeignKey("UnityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnityObject");
                });

            modelBuilder.Entity("CompenseAgora.Entities.TypeEnergyGasEntity", b =>
                {
                    b.HasOne("CompenseAgora.Entities.TypeEnergyEntity", "TypeEnergyObject")
                        .WithMany()
                        .HasForeignKey("TypeEnergyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeEnergyObject");
                });
#pragma warning restore 612, 618
        }
    }
}
